pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = "your-aws-region"
        AWS_DEFAULT_OUTPUT = "json" // or yaml
        PROJECT_DIR = "Full Path/Serverless AI Email Newsletter" 
    }
    
    stages {
        stage("Install Python Libraries For Lambda") {
            steps {
                dir(env.PROJECT_DIR) {
                    powershell '''
                        if (-not (Test-Path "lambdacode/requests/__init__.py") -or (-not (Test-Path "lambdacode/psycopg/__init__.py"))) {
                        	docker build -t custom_image .
                        	docker create --name custom_container custom_image
                        	docker cp custom_container:/home/lambdacode/. ./lambdacode
                        	docker rm custom_container; docker rmi custom_image
                        	Write-Host "Installed Libraries"
                        
                        } else { Write-Host "Libraries are already installed." }
                    '''
                }
            }
        }

        stage("Zip Lambda Code And Upload To S3") {
            steps {
                dir(env.PROJECT_DIR) {
                    withCredentials([usernamePassword(credentialsId: "aws-cred", passwordVariable: "AWS_SECRET_ACCESS_KEY", usernameVariable: "AWS_ACCESS_KEY_ID")]) {
                        powershell '''
                            & "C:/Program Files/7-Zip/7z.exe" a -tzip lambda_function.zip ./lambdacode/*
                            aws s3 cp lambda_function.zip s3://bucket-name/lambda_function.zip
                        '''
                    }
                }
            }
        }
        
        stage("Deploy Cloudformation Template") {
            steps {
                dir(env.PROJECT_DIR) {
                    withCredentials([
                        usernamePassword(
                            credentialsId: "aws-cred", 
                            passwordVariable: "AWS_SECRET_ACCESS_KEY", 
                            usernameVariable: "AWS_ACCESS_KEY_ID"
                        ),

                        string(credentialsId: "EMAIL", variable: "EMAIL_ID"),
                        string(credentialsId: "EMAILPASSWORD", variable: "EMAIL_PASSWORD"),
                        string(credentialsId: "GROQAPI", variable: "API_KEY")
                    ]) {

                        powershell '''
                            aws cloudformation deploy `
                            --template-file stack.yaml `
                            --stack-name test-stack `
                            --capabilities CAPABILITY_IAM `
                            --parameter-overrides Email="$env:EMAIL_ID" Password="$env:EMAIL_PASSWORD" GroqKey="$env:API_KEY" `
                            --no-fail-on-empty-changeset
                            
                            aws cloudformation wait stack-create-complete --stack-name test-stack
                        '''
                    }
                }
            }
        }

        stage("Upload Website Content To S3 And Create Table In DSQL") {
            steps {
                dir(env.PROJECT_DIR) {
                    withCredentials([usernamePassword(credentialsId: "aws-cred", passwordVariable: "AWS_SECRET_ACCESS_KEY", usernameVariable: "AWS_ACCESS_KEY_ID")]) {
                        powershell '''
                            $data = aws cloudformation describe-stacks --stack-name test-stack --output json | ConvertFrom-Json
                            $api_url = ($data.Stacks.Outputs | Where-Object Outputkey -eq "APIBASEURL").OutputValue
                            $dsql_endpoint = ($data.Stacks.Outputs | Where-Object Outputkey -eq "DSQLENDPOINT").OutputValue

                            (Get-Content staticpage/index.html) -replace 'const base_url = "[^"]*"', "const base_url = `"$($api_url)`"" | Set-Content staticpage/index.html 
                            aws s3 sync staticpage s3://astronomy-news-sample

                            $Token = aws dsql generate-db-connect-admin-auth-token --hostname $dsql_endpoint
                            $env:PGPASSWORD = $Token

                            & "C:/Program Files/PostgreSQL/18/bin/psql.exe" -h $dsql_endpoint -U admin -d postgres -c "CREATE TABLE astronomy_subscribers (
                                email TEXT PRIMARY KEY,
                                token TEXT NOT NULL,
                                expires_at TIMESTAMPTZ,
                                verified BOOLEAN NOT NULL DEFAULT FALSE
                            );"
                        '''
                    }
                }
            }
        }
    }
}